backend:
  name: github
  repo: sim1gariglio/SitoProva
  branch: main
  base_url: https://prazdevs-decap-cms-proxy.prazdevs.com # Questo Ã¨ il proxy

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Articoli"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Immagine", name: "image", widget: "image", required: false}
      - {label: "Testo Articolo", name: "body", widget: "markdown"}

