backend:
  name: github
  repo: sgariglio/SitoProva # Esempio: mario-rossi/sito-pedagogista
  branch: main # Assicurati che il tuo branch principale si chiami main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "blog"
    label: "Articoli Blog"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Immagine Copertina", name: "image", widget: "image", required: false }
      - { label: "Testo Articolo", name: "body", widget: "markdown" }