backend:
  name: github
  repo: sim1gariglio/SitoProva
  branch: main

media_folder: "/images"
public_folder: "/images"

collections:
  - name: "articoli"
    label: "Articoli"
    folder: "content/articoli"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Testo", name: "body", widget: "markdown" }